name: Schedule - Cypress API Tests
on:
  schedule:
    - cron: '* * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name : Clone repository
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6